/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AccountIndexImport } from './routes/account/index'
import { Route as ImageTinyLmgIndexImport } from './routes/image/tiny-lmg/index'
import { Route as ImageGeneratorIndexImport } from './routes/image/generator/index'
import { Route as ImageFormatterIndexImport } from './routes/image/formatter/index'
import { Route as AuthVerifyEmailIndexImport } from './routes/auth/verify-email/index'
import { Route as AuthSignupIndexImport } from './routes/auth/signup/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminUsersIdIndexImport } from './routes/admin/users/$id/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIndexRoute = AccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const ImageTinyLmgIndexRoute = ImageTinyLmgIndexImport.update({
  id: '/image/tiny-lmg/',
  path: '/image/tiny-lmg/',
  getParentRoute: () => rootRoute,
} as any)

const ImageGeneratorIndexRoute = ImageGeneratorIndexImport.update({
  id: '/image/generator/',
  path: '/image/generator/',
  getParentRoute: () => rootRoute,
} as any)

const ImageFormatterIndexRoute = ImageFormatterIndexImport.update({
  id: '/image/formatter/',
  path: '/image/formatter/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexImport.update({
  id: '/auth/verify-email/',
  path: '/auth/verify-email/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupIndexRoute = AuthSignupIndexImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersIdIndexRoute = AdminUsersIdIndexImport.update({
  id: '/admin/users/$id/',
  path: '/admin/users/$id/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailIndexImport
      parentRoute: typeof rootRoute
    }
    '/image/formatter/': {
      id: '/image/formatter/'
      path: '/image/formatter'
      fullPath: '/image/formatter'
      preLoaderRoute: typeof ImageFormatterIndexImport
      parentRoute: typeof rootRoute
    }
    '/image/generator/': {
      id: '/image/generator/'
      path: '/image/generator'
      fullPath: '/image/generator'
      preLoaderRoute: typeof ImageGeneratorIndexImport
      parentRoute: typeof rootRoute
    }
    '/image/tiny-lmg/': {
      id: '/image/tiny-lmg/'
      path: '/image/tiny-lmg'
      fullPath: '/image/tiny-lmg'
      preLoaderRoute: typeof ImageTinyLmgIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/users/$id/': {
      id: '/admin/users/$id/'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/image/formatter': typeof ImageFormatterIndexRoute
  '/image/generator': typeof ImageGeneratorIndexRoute
  '/image/tiny-lmg': typeof ImageTinyLmgIndexRoute
  '/admin/users/$id': typeof AdminUsersIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/image/formatter': typeof ImageFormatterIndexRoute
  '/image/generator': typeof ImageGeneratorIndexRoute
  '/image/tiny-lmg': typeof ImageTinyLmgIndexRoute
  '/admin/users/$id': typeof AdminUsersIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/image/formatter/': typeof ImageFormatterIndexRoute
  '/image/generator/': typeof ImageGeneratorIndexRoute
  '/image/tiny-lmg/': typeof ImageTinyLmgIndexRoute
  '/admin/users/$id/': typeof AdminUsersIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/admin/users'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/image/formatter'
    | '/image/generator'
    | '/image/tiny-lmg'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/admin/users'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/image/formatter'
    | '/image/generator'
    | '/image/tiny-lmg'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/account/'
    | '/admin/'
    | '/auth/'
    | '/admin/users/'
    | '/auth/login/'
    | '/auth/signup/'
    | '/auth/verify-email/'
    | '/image/formatter/'
    | '/image/generator/'
    | '/image/tiny-lmg/'
    | '/admin/users/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
  ImageFormatterIndexRoute: typeof ImageFormatterIndexRoute
  ImageGeneratorIndexRoute: typeof ImageGeneratorIndexRoute
  ImageTinyLmgIndexRoute: typeof ImageTinyLmgIndexRoute
  AdminUsersIdIndexRoute: typeof AdminUsersIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
  ImageFormatterIndexRoute: ImageFormatterIndexRoute,
  ImageGeneratorIndexRoute: ImageGeneratorIndexRoute,
  ImageTinyLmgIndexRoute: ImageTinyLmgIndexRoute,
  AdminUsersIdIndexRoute: AdminUsersIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account/",
        "/admin/",
        "/auth/",
        "/admin/users/",
        "/auth/login/",
        "/auth/signup/",
        "/auth/verify-email/",
        "/image/formatter/",
        "/image/generator/",
        "/image/tiny-lmg/",
        "/admin/users/$id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/account/": {
      "filePath": "account/index.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/signup/": {
      "filePath": "auth/signup/index.tsx"
    },
    "/auth/verify-email/": {
      "filePath": "auth/verify-email/index.tsx"
    },
    "/image/formatter/": {
      "filePath": "image/formatter/index.tsx"
    },
    "/image/generator/": {
      "filePath": "image/generator/index.tsx"
    },
    "/image/tiny-lmg/": {
      "filePath": "image/tiny-lmg/index.tsx"
    },
    "/admin/users/$id/": {
      "filePath": "admin/users/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
